### ISSUE TITLE
Minor changes to the 3.0 API

### ISSUE THREAD

**Issue by Marc010** [HaxePunk/HaxePunk#347]
@ibilon
I would suggest some minor changes to the proposed 3.0 API:

1. if Value is the baseclass for all classes in the values package it should be located in the root folder to match the other baseclasses (Graphic, Mask, Filter, ...)
2. 'AnimatedImage' should be renamed to something shorter, maybe just 'Animation' and then name the current HXP 2.0 Animation 'AnimationDefinition' because the definition itself is often only used internally
3. there should be an EntityList (abstract over Array<Entity>) with some helper functions like filtering out every entity that isn't in a specific group, ... that is used as return type instead of Array<Entity>
4. default values should be saved in a static anonymous object consistently for every class requiring them instead of being passed to the constructor to help the garbage collection
5. Remvoe whitespace after/before a type 'public var width : Float -> public var width:Float'
6. Make Outside a variable of the Mask class, it's also useful for TileMaps

If these changes are ok, i'll make a pull request..
Also besides that the API looks very nice :)

**Comment by ibilon** [comment]
Thanks for your input!

1. I'm not yet 100% sure on how to deal with this, but it'll probably end up like this yeah.
2. True, it's indeed a bit long.
3. Nice idea.
4. Defaults value aren't passed to the constructor, it's not clear yet because I wrote that a bit quickly but you, optionally, pass an object with some config, but they're all optional, and the ones that you don't put in the object are replaced with some default value.
5. I absolutely want regularity in the entire code base, I just often forget the convention :) I'll tidy everything once the api is settled ;)
6. Not completely sure what you mean by that, it's supposed to be a mask type. Well actually I changed it (not yet commited) to `Invert<T:Mask> extends T` that will change any Mask to it's opposite and not just for Box. So you could make an Entity with a TileMap as graphic and a `Invert<Box>` as mask. 

Note that for now there's only the part of the api that currently exists,
still missing: physics wrapper, ui, networking, the 3d part: mesh, light, the plugin system, better tweening and a drawing api. Still a lot a work =)

**Comment by Marc010** [comment]
4. Ok this makes it more clear. I thought a config can either contain all values or be null but i think my suggestion to keep the default values in one static var per class.
I made a little example of how i would like to implement it: http://try.haxe.org/#59Bc2

6. My idea was to add a outside:Bool to the mask class which basically just inverts all results. But nevermind, your idea is fancier :)

Also for the plugin system it should be enough to implement a few signals for important events like updating, rendering and game paused if i'm not missing anything.

**Comment by ibilon** [comment]
1. Yeah, I've seen several case where people asked if there was an easy way to change a default beside extending the class, so this'll be definitively useful

For the plugin system: I can also a couple for the debug console since it pause the game, probably something for scene change, entity add/remove stuff like that.
Will probably need two version for each signal: before and after.

A question is how much control can a plugin have. For instance in the onBeforeX can it cancel the call.

**Comment by Murii** [comment]
How much time should I wait till I can start learning/using the new api?

**Comment by ibilon** [comment]
If you have time you should check it out and tell us how you feel about it, though that may be hard just looking at the source files. When the draft is complete I'll write demos (well demo code since it's just the api) then it'll be easier.

For learning I'd say not before 3.0 becomes a beta, until then it may still change.

Once it's in beta you'll be able to use the new version (also on old 2.X projects using the compatibility layer we'll provide) at that point the api will be fixed and there'll be documentation so you might as well start to learn/use it.

As for when all that will be no idea, the project took time to launch (first discussed around June) and there's a lot of code to write.

**Comment by Marc010** [comment]
@ibilon 
1. What's the point of the Shape classes? We should avoid to have 2 Classes with the same name (autocompletion normally doesn't handle this very well).
2. 'flippedHorizontally' is a bit too long, i think 'flipX' is descriptive enough

**Comment by ibilon** [comment]
1. I wasn't very happy about this either, in the "old" api Image have 3 create functions: circle, rectangle and polygon. The first two have regular parameters, radius/width-height, but createPolygon uses a polygon mask.
I wanted to avoid code duplication but thinking about it more the shape thing really is useless, and a big problem with the name duplication, I'll just copy the create methods of the polygon mask class and add a fromMask function to Image.

2. On one hand I don't like names that are too long and on the other I don't like abbreviation, well here flipX works.

3. Here's a big api problem, how much do we "contract" things.
Like should width/height be replaced by size?
Should Rectangle be x/y/width/height or point/size?

4. Yeah I guess the "randomness" is already indicated by the class name.

**Comment by Murii** [comment]
Ok,I understand your point.But please can you tell me how many seconds you need  in order to compile your projects to neko?

**Comment by ibilon** [comment]
Well why not? That's with the default haxepunk template so obviously the more code you have the longer it'll take
```
time lime build neko // first time
real    0m5.467s
user    0m2.371s
sys     0m0.223s

time lime build neko // second+ time
real    0m3.018s
user    0m2.366s
sys     0m0.174s
```

**Comment by Marc010** [comment]
3. Good point. I think Rectangle should stay as it is because using Size doesn't add anything and makes it different from 99% of the existing Rectangle implementions :)
I think it's a good idea to make all Values abstracts. That avoids some new() boilerplate code.
e.g.
player.position = new Point(x, y); -> player.position = [x, y]

**Comment by ibilon** [comment]
Definitively abstracts yeah, mainly so we can overload operators `player.position += velocity`.
Didn't thought of this syntax but it's nice, and way sorter.

**Comment by Marc010** [comment]
How do we handle tweens in this case?
´´´
tween(player.position);
player.position = [5, 7] // the tween now has an outdated reference
player.position = player.position + velocity // same here
player.position += velocity // works, assign_add modifies the existing point instance
´´´

**Comment by ibilon** [comment]
We'll have to tie the tween to the property and not the object, like now.
Normally with a macro it shouldn't be a problem.
Transforming `player.position.tweenTo([5, 7], 3);` to `Point.createTween("player.position", player.position, [5,7], 3);` or something like that.

**Comment by Marc010** [comment]
I think the functions screenShake, stopScreenShake, and capture could be moved to the Camera class, especially the last one requires much code to work on both backends.
Also Gamepads hat var should be an Array.

**Comment by ibilon** [comment]
You're right that could be useful to have these in the Camera class too, but since the screen can have multiple cameras they shouldn't be removed from Engine. I'll rename them shake/stopShake so they'll have the same name in both classes.

Indeed it should.

**Comment by MattTuttle** [comment]
I'm closing this in favor of keeping track of this on trello. If you'd like access to the boards for commenting just let me know. https://trello.com/b/JT35cU1i
