### ISSUE TITLE
Examples demo messed up backdrop on native

### ISSUE THREAD

**Issue by scriptorum** [HaxePunk/HaxePunk#352]
When using [ and ] to switch demo scenes, sometimes some of the bitmaps on the platformer and emitter demos will not render correctly on native targets. The bitmap data appears to have a corrupt reference, for example:

![screen shot 2015-01-05 at 4 53 09 pm](https://cloud.githubusercontent.com/assets/3144427/5620692/21c6c6a2-94fc-11e4-9a51-db4da789d0c5.png) ![screen shot 2015-01-05 at 5 04 00 pm](https://cloud.githubusercontent.com/assets/3144427/5620765/e3e13d62-94fc-11e4-9300-921d1000349d.png) ![screen shot 2015-01-05 at 5 10 02 pm](https://cloud.githubusercontent.com/assets/3144427/5620847/c3efd9ae-94fd-11e4-9837-dd446fea5eb2.png) ![screen shot 2015-01-05 at 5 11 35 pm](https://cloud.githubusercontent.com/assets/3144427/5620862/f21a98b4-94fd-11e4-98a8-39ca29efd4bf.png)

Generally cycling in order is fine, and can also restore the correct bitmaps. To demonstrate the issue, run the examples demo, cycle forward ] to the platformer demo and back [ to the emitter demo. I'm not sure what the cause is yet, but it has something to do with how these demos use TextureAtlases on native. By removing atlas.destroy() calls in those demos, the bitmap corruption disappears. 

```haxe
	public override function end()
	{
#if !flash
		atlas.destroy();
#end
	}
```

I considered that maybe I caused this issue in pull request https://github.com/HaxePunk/HaxePunk/pull/351, but the problem exists when tested against the release build.

**Comment by Marc010** [comment]
This one is really weird. I used the example project from git (wasn't updated since a while anyways) and the latest haxelib release.
Windows 7 64-bit, cpp:
'lime build windows'
'lime run windows'
![started](https://cloud.githubusercontent.com/assets/5739192/5629761/375068c8-95b7-11e4-8b16-40efc47149c5.PNG)
pressing forward
![1 -forward](https://cloud.githubusercontent.com/assets/5739192/5629775/553ec8c0-95b7-11e4-92ff-3f8dd95f3f99.PNG)
back again
![2 - back](https://cloud.githubusercontent.com/assets/5739192/5629778/5c253fe8-95b7-11e4-9ca9-d411ce6ed09a.PNG)
If i cycle to the third scene and back to the second, it's working
![working](https://cloud.githubusercontent.com/assets/5739192/5629785/731b5156-95b7-11e4-9662-3579de1b6549.PNG)
back to the first scene again
![3 - back](https://cloud.githubusercontent.com/assets/5739192/5629808/aa761fe6-95b7-11e4-88ce-dc787198ed73.PNG)

I can't find the cause of the bug in the HaxePunk code, could it be a openfl/lime bug?
i'll test it again with different openfl versions later.

HaxePunk: [2.5.3]
hxcpp: [3.1.48]
lime: [2.0.4]
openfl: [2.2.1]

**Comment by scriptorum** [comment]
Explicitly destroying an atlas is going to invalidate any other atlas referencing the same bitmap. The way this currently works, I'm scratching my head trying to come up with a way to detect this condition and throw an error. 

What if we remove HXP.removeBitmap() from AtlasData.destroy()? With this change, all implicitly-loaded bitmaps are always cached. Bitmaps can only be removed, then, if you explicitly do so yourself. Any consequences to this? Are any HaxePunk users actually calling atlas.destroy()?
