### ISSUE TITLE
Sorry for posting here

### ISSUE THREAD

**Issue by Murii** [HaxePunk/HaxePunk#353]
Hello,If I follow the documentation for installing haxepunk will it work for version 3.0? Like  installing haxe 3.0.1 instead of 3.1.3 and so on.Thanks!

**Comment by scriptorum** [comment]
It might work, but we recommend using the latest Haxe version 3.1.3, which [fixes numerous bugs](http://haxe.org/file/CHANGES.txt) and introduces new language features that HaxePunk, OpenFL and Lime might rely upon. Is there some reason you don't want to use the latest Haxe?

Another place to ask questions like this is the [HaxePunk forums](http://forum.haxepunk.com), which may get more attention. This is more for bug reports and feature requests.

**Comment by Murii** [comment]
I dont have any problems using the latest Haxe version but on the documentation page I saw I need to  install version 3.0.1 and that`s why I asked.Thanks for your answer!

**Comment by ibilon** [comment]
We need to update the getting started page, now that haxe 3 is really in place there's probably no reason to warn about the 2.10 version.
Also for linux we should probably also link to the openfl installer (http://www.openfl.org/builds/haxe/haxe-3.1.3-linux-installer.tar.gz) instead of having the user to figure out how to manually install haxe&neko.

**Comment by scriptorum** [comment]
I removed the (old) versions from the Getting Started page, and added the information about the Linux install script.
