### ISSUE TITLE
Class not found: BitmapData when autocompleting in sublime text

### ISSUE THREAD

**Issue by stasuss** [HaxePunk/HaxePunk#363]
HaxePunk broke autocomplete of sublime text plugin autocompletion. It just shows that error message on statusbar and fails to show suggestions.

However compilation is succesful.
I think it happens already when using HXP class. I mean Main.hx. When I type here HXP and press dot, I already have no completions. Don't know where specifically this error comes from.
Tried importing openfl's and haxe's BitmapData classes - no help.

How can I localize this error? It is really unpleasant to code without completions :-)

**Comment by scriptorum** [comment]
Issue crossposted here: https://github.com/clemos/haxe-sublime-bundle/issues/217.

Does autocompletion work for you without HaxePunk? That is, if you just use OpenFL, and create something like this, do you get a similar issue after typing `openfl.Lib.`?

```haxe
package;
class Main extends openfl.display.Sprite
{
	public function new () 
	{
		super();
		openfl.Lib. ...
	}
}
```

TBH I've never gotten Haxe completions to work properly in Sublime, let alone HaxePunk.

**Comment by stasuss** [comment]
yes. haxepunk only.

**Comment by scriptorum** [comment]
As I said, I never had code completion working in Sublime, but I can diagnose this a bit. I entered "`HXP.`" into the HaxePunk demo Main.hx, saved it, and ran `lime display neko`. I then took the arguments output, joined them, and ran `haxe <thoseargs> --display src/Main.hx@125` (where 125 is the position of "`HXP.`"). This generated the following XML:

```xml
<list>
	<i n="DEG">
		<t>Float</t>
		<d>Convert a radian value into a degree value. </d>
	</i>
	<i n="INT_MAX_VALUE">
		<t>Int</t>
		<d>* Flash equivalent: int.MAX_VALUE
	 </d>
	</i>
	<i n="INT_MIN_VALUE">
		<t>Int</t>
		<d>* Flash equivalent: int.MIN_VALUE
	 </d>
	</i>
	<i n="NUMBER_MAX_VALUE">
		<t>Float</t>
		<d>* Flash equivalent: Number.MAX_VALUE
	 </d>
	</i>
	<i n="RAD">
		<t>Float</t>
		<d>Convert a degree value into a radian value. </d>
	</i>
[...snip...]
```

This tells me that on my system, HaxePunk is not doing anything to prevent code completion. If your code completion is working with other libraries, just not HaxePunk, it could be something in your source files, outdated libraries, or odd platform configuration that the sublime haxe package cannot parse correctly.  Does this issue occur if you enter `HXP.`into `HaxePunk/examples/src/Main.hx`?

I suppose I should submit my own sublime issue for the "could not process argument" errors I get...

**Comment by stasuss** [comment]
may you explain how is 125 value calculated? i wanna make such experiment on my side, to exclude sublime itself. i can't understand how to count from  line\col notation/

**Comment by scriptorum** [comment]
Sure. I used the Sublime package WordCount and selected from the start of the file down to and including the text `HXP.`. WordCount reports the selected character count on the status line.

**Comment by stasuss** [comment]
so. it worked. but i was hoping that it does not and so i can mess with libraries to solve the issue.
conclusion: it is purely plugin issue :-(

**Comment by scriptorum** [comment]
I was able to [resolve my issue](https://github.com/clemos/haxe-sublime-bundle/issues/218) with the Sublime Haxe package last night, by renaming my export path to TitleCase. Completion with HXP works fine. I wonder if there's something similar with your problem, something weird with the format of your project.xml file?

If I understand you correctly, you're asking how the issue systems work on GitHub. Each account can have multiple repositories, and each repository has its own issue tracker. [THIS issue tracker](https://github.com/HaxePunk/HaxePunk/issues) is just for HaxePunk issues only. You can see in the url github.com/ACCOUNT/REPO/issues. The Sublime Haxe package has its own [issue tracker](https://github.com/clemos/haxe-sublime-bundle/issues).

We've isolated this as not an issue with HaxePunk in particular, so I'm going to close this issue here. You can pursue this further with the other issue [you opened on haxe-sublime-bundle](https://github.com/clemos/haxe-sublime-bundle/issues/217) or by posting on the [HaxePunk forums](http://forum.haxepunk.com) where maybe someone else has experienced this problem.
