### ISSUE TITLE
HXP.volume/pan working on flash only

### ISSUE THREAD

**Issue by rpidstryhach** [HaxePunk/HaxePunk#367]
I've tried neko and mac native builds and global volume/panning won't work there. I thought of multiplying volume in `Sfx.play()` method by `HXP.volume` (and same goes for pan), but realised this won't affect sounds that are already playing. Any thoughts?

**Comment by scriptorum** [comment]
This is an [OpenFL issue](http://community.openfl.org/t/solved-audio-soundtransform-panning-issue-targeting-neko/957), or rather a limitation of the OpenAL sound library. Convert your sound to mono to support native panning effects.

**Comment by rpidstryhach** [comment]
Got it, thanks!

**Comment by scriptorum** [comment]
Sorry, I was fixating on the panning problem.

I don't think it'll fix the global volume issue. [SoundMixer isn't supported in OpenFL](https://github.com/openfl/openfl-native/issues/129), which is what we're using on Flash to set global volume. You could try to set volumes en masse using something like `Sfx.setVolume("", myVolume)`, assuming you're not already using Sfx *types* and individual volumes are not being tweaked. 

I'll reopen the issue, since we really should have a working global volume.

**Comment by scriptorum** [comment]
Global volume and panning are now respected by the Sfx class, and on native targets all sound effects are updated whenever the global volume or panning is altered. HaxePunk commit: https://github.com/HaxePunk/HaxePunk/commit/6758c978fa2e9a33ea0e89ee43e2d5f670f3b90c.

**Comment by rpidstryhach** [comment]
Works like a charm, thanks!
