### ISSUE TITLE
Polygon Hitbox not working

### ISSUE THREAD

**Issue by 96AA48** [HaxePunk/HaxePunk#383]
I'm working on a game and I made a simple Physics object that can collide with a type called `ground`. I've assigned this type to an object with a polygon hitbox, [but for some reason](http://i.imgur.com/O1bVLX9.png), it collides with the outer red square instead of the inner (blue) polygon hitbox. The implementation of the `collide` in the Physics object is as follows.

``` haxe
package entities;

import com.haxepunk.Entity;
import com.haxepunk.HXP;
import com.haxepunk.graphics.Image;

import entities.Ground;

class Physics extends Entity {
  public override function new(x:Float, y:Float) {
    super(x, y);
    setHitbox(25, 25);
    graphic = Image.createRect(25, 25, 0xFF0000);
    layer = -1 ;
  }

  public override function update() {
    super.update();

    if (!grounded) speedY += (9.81 * HXP.elapsed);
    if (!grounded && collide("ground", this.x, this.y) != null) {
      trace('Got the ground');
      grounded = true;
      speedY = 0;
    }

    if (grounded && collide("ground", this.x, this.y) == null) {
      trace('Fly my bredren');
      grounded = false;
    }

    this.y += speedY;
  }

  public var grounded:Bool = false;
  private var speedY:Float = -9;
}

```

And the bridge (called `Tower.hx`) like this : 

``` haxe
package environment;

import com.haxepunk.Entity;
import com.haxepunk.graphics.Image;
import com.haxepunk.masks.Polygon;

class Tower extends Entity {
  public override function new() {
    super(0, 60);
    graphic = new Image("graphics/towers_front.png");
    this.layer = -2;

    var poly:Polygon = Polygon.createFromArray([
      56, 56,
      290, 172,
      350, 172,
      582, 56,
      582, 62,
      355, 178,
      284, 178,
      56, 62
      ]);

    mask = poly;

    type = "ground";
  }

}
```

It seems like the hitboxes aren't working the way they're supposed to. Either that or I'm a shit programmer (most likely). Thanks for your time.

**Comment by matrefeytontias** [comment]
I took a look to the different collide functions in Polygon.hx, and yes, there is a breaking bug indeed. What the code does to check collision is to project the polygon and the other entity's mask onto the two axis (X and Y), and it assumes the two objects collide if the two projections overlap in both cases. In easier form, it means that the mask is inside the polygon, or the other way around. While it does work with convex polygons, it can and will break with any polygon that is not convex. I'm pretty sure that the entirety of the Polygon class's collide functions need to be rewritten in order to work with any type of polygon. So yeah, your code is fine, don't worry about that.

**Comment by 96AA48** [comment]
Hey @matrefeytontias,
Thanks for your suggestion. I came up with a solution shortly after submitting this issue that's basically what you suggested. I changed the mask to a MaskList that contains several polygons instead of just one big polygon and it works.

Thanks for your time.

I'll just keep this issue open for when someone is able to fix it.

**Comment by matrefeytontias** [comment]
Bump, I'll handle that when I'm done with my current project (that is, soon enough).

**Comment by forgotten-king** [comment]
@matrefeytontias was this fixed with your latest addition of "non-convex" polygons?

**Comment by matrefeytontias** [comment]
It was yes.
