### ISSUE TITLE
"Useage of this typedef is deprecated"

### ISSUE THREAD

**Issue by raould** [HaxePunk/HaxePunk#490]
- **HaxePunk version:** 2.6.1
- **Target(s):** neko
- **Haxe version:** 3.4.2
- **OpenFL/Lime or NME version:** 5.0.3

Probably something about me using the wrong too-new versions of lime or something? I think it would be good if the[ install/setup page](http://haxepunk.com/documentation/tutorials/getting-started/) would tell us exactly what versions we're supposed to be using. :-)

Although note that I just re-ran "$ haxelib run HaxePunk setup" and it didn't change the versions of openfl or lime at all, so either it is a different issue than version mismatch, or the setup script is also borken?

lime build neko
/usr/local/haxelib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/HardwareRenderer.hx:28: characters 21-23 : Warning : Usage of this typedef is deprecated

$ haxelib list
HaxePunk: [2.6.1]
hxcpp: [3.4.64]
lime-samples: [4.0.1]
lime: [5.0.3]
mconsole: [1.6.0]
mcover: [2.1.1]
mlib: [2.0.2]
munit: [2.1.2]
openfl: [5.1.2]
thx.core: [0.42.1]
thx.unit: [0.8.0]

**Comment by bendmorris** [comment]
>Probably something about me using the wrong too-new versions of lime or something?

That's it, the warning is coming from Lime. If things are generally working, you can probably ignore the warning and just know that it may stop working eventually in a new Lime version.

`haxelib run HaxePunk setup` will install the dependencies as specified in haxelib.json; unfortunately this means that it'll always install the latest OpenFL and Lime since we don't require a specific version, and this might not be what most users want. Haxelib doesn't give us very good control over which versions to accept though, and I'd rather not tie the project to one specific version when a range of versions should work. I think this ultimately needs to be solved by improvements to haxelib.

**Comment by SunShiranui** [comment]
Wouldn't it still be desirable to give a reference OpenFL\Lime version with each release, so new users don't risk ending up with incompatible dependencies after running setup?

**Comment by bendmorris** [comment]
Essentially the versions in .travis.yml are the ones we test against and officially support; you should be able to use any of those. We can't put a specific reference version in haxelib.json though because it won't allow users to run with alternate versions. There's some movement to improve haxelib recently so hopefully this will become a non-issue soon enough.
